### ISSUE TITLE
A simpler way to express the largest-of-four problem

### ISSUE THREAD

**Issue by samwho** [GemzFr/hr-challenges#3]
https://github.com/GemzFr/hr-challenges/blob/d80840a3a55e8b0b65fd2ac72ebc772fcc62f6f1/fcc-exercises/arr-highest-value.js#L1-L9

```
function largestOfFour(arr) {
  return arr.map(a => Math.max(...a));
}
```

**Comment by GemzFr** [comment]
Added to the file, thanks!
